/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/jaylin/Projects/EdgeComputing/dds2mqtt/build/HelloWorld.h
  Source: /home/jaylin/Projects/EdgeComputing/dds2mqtt/cyclonedds/HelloWorld.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_JAYLIN_PROJECTS_EDGECOMPUTING_DDS2MQTT_BUILD_HELLOWORLD_H
#define DDSC__HOME_JAYLIN_PROJECTS_EDGECOMPUTING_DDS2MQTT_BUILD_HELLOWORLD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum test_enum
{
  enum1,
  enum2
} test_enum;

#define test_enum__alloc() \
((test_enum*) dds_alloc (sizeof (test_enum)));

typedef struct test_struct
{
  uint8_t message[256];
} test_struct;

extern const dds_topic_descriptor_t test_struct_desc;

#define test_struct__alloc() \
((test_struct*) dds_alloc (sizeof (test_struct)));

#define test_struct_free(d,o) \
dds_sample_free ((d), &test_struct_desc, (o))

typedef struct example_struct
{
  int8_t int8_test;
  uint8_t uint8_test;
  int16_t int16_test;
  uint16_t uint16_test;
  int32_t int32_test;
  uint32_t uint32_test;
  int64_t int64_test;
  uint64_t uint64_test;
  uint8_t message[256];
  test_enum example_enum;
  struct test_struct example_stru;
} example_struct;

extern const dds_topic_descriptor_t example_struct_desc;

#define example_struct__alloc() \
((example_struct*) dds_alloc (sizeof (example_struct)));

#define example_struct_free(d,o) \
dds_sample_free ((d), &example_struct_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_JAYLIN_PROJECTS_EDGECOMPUTING_DDS2MQTT_BUILD_HELLOWORLD_H */
